In [1]:
import warnings
warnings.simplefilter('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
from sklearn import decomposition #pca
from sklearn.preprocessing import StandardScaler # Standardization ((X - X_mean)/X_std)
from sklearn.neighbors import KNeighborsClassifier #KNN Model
from sklearn.ensemble import RandomForestClassifier #RandomForest Model
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression #Logistic Model
from sklearn.linear_model import LogisticRegressionCV
from sklearn.svm import SVC
from sklearn.model_selection import KFold

from sklearn.model_selection import train_test_split # Splitting into train and test
from sklearn import metrics
from sklearn.metrics import accuracy_score

from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
import xgboost
from xgboost import XGBClassifier

from sklearn.model_selection import RandomizedSearchCV,GridSearchCV# Hyperparameter Tuning
from sklearn.model_selection import cross_val_score#cross validation score
from sklearn.metrics import classification_report # text report showing the main classification metrics
from sklearn.metrics import confusion_matrix #to get confusion_matirx 
import matplotlib.pyplot as plt
import pickle

In [3]:
clean_df=pd.read_csv('clean_data.csv')

In [4]:
clean_df.head()

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0   50       2     168      62    110     80            1     1      0     0   
1   55       1     156      85    140     90            3     1      0     0   
2   52       1     165      64    130     70            3     1      0     0   
3   48       2     169      82    150    100            1     1      0     0   
4   48       1     156      56    100     60            1     1      0     0   

   active  cardio  bmi  pulse  
0       1       0   22     30  
1       1       1   35     50  
2       0       1   24     60  
3       1       1   29     50  
4       0       0   23     40

In [5]:
def transform_age(age):
    if age >= 18 and age <= 37:
        return 1
    elif age >= 38 and age <= 45:
        return 2
    elif age >= 46 and age <= 53:
        return 3
    elif age >= 54 and age <= 61:
        return 4
    elif age >= 62 and age <= 69:
        return 5
    elif age >= 70 and age <= 80:
        return 6

clean_df = clean_df.assign(final_age = clean_df['age'].apply(transform_age))
clean_df.tail()
    

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
64647   53       2     168      76    120     80            1     1      1   
64648   62       1     158     126    140     90            2     2      0   
64649   52       2     183     105    180     90            3     1      0   
64650   61       1     163      72    135     80            1     2      0   
64651   56       1     170      72    120     80            2     1      0   

       alco  active  cardio  bmi  pulse  final_age  
64647     0       1       0   27     40          3  
64648     0       1       1   50     50          5  
64649     1       0       1   31     90          3  
64650     0       0       1   27     55          4  
64651     0       1       0   25     40          4

In [6]:
def transform_hp(ap_hi):
    if ap_hi >= 60 and ap_hi <= 89:
        return 1
    elif ap_hi >= 90 and ap_hi <= 119:
        return 2
    elif ap_hi >= 120 and ap_hi <= 129:
        return 3
    elif ap_hi >= 130 and ap_hi <= 139:
        return 4
    elif ap_hi >= 140 and ap_hi <= 179:
        return 5
    elif ap_hi >= 180 and ap_hi <= 370:
        return 6

clean_df = clean_df.assign(final_ap_hi = clean_df['ap_hi'].apply(transform_hp))
clean_df.tail()
    

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
64647   53       2     168      76    120     80            1     1      1   
64648   62       1     158     126    140     90            2     2      0   
64649   52       2     183     105    180     90            3     1      0   
64650   61       1     163      72    135     80            1     2      0   
64651   56       1     170      72    120     80            2     1      0   

       alco  active  cardio  bmi  pulse  final_age  final_ap_hi  
64647     0       1       0   27     40          3            3  
64648     0       1       1   50     50          5            5  
64649     1       0       1   31     90          3            6  
64650     0       0       1   27     55          4            4  
64651     0       1       0   25     40          4            3

In [7]:
def transform_lp(ap_lo):
    if ap_lo >= 30 and ap_lo <= 60:
        return 1
    elif ap_lo >= 61 and ap_lo <= 79:
        return 2
    elif ap_lo >= 80 and ap_lo <= 89:
        return 3
    elif ap_lo >= 90 and ap_lo <= 99:
        return 4
    elif ap_lo >= 100 and ap_lo <= 109:
        return 5
    elif ap_lo >= 110 and ap_lo <= 360:
        return 6

clean_df = clean_df.assign(final_ap_lo = clean_df['ap_lo'].apply(transform_lp))
clean_df.tail()
    

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
64647   53       2     168      76    120     80            1     1      1   
64648   62       1     158     126    140     90            2     2      0   
64649   52       2     183     105    180     90            3     1      0   
64650   61       1     163      72    135     80            1     2      0   
64651   56       1     170      72    120     80            2     1      0   

       alco  active  cardio  bmi  pulse  final_age  final_ap_hi  final_ap_lo  
64647     0       1       0   27     40          3            3            3  
64648     0       1       1   50     50          5            5            4  
64649     1       0       1   31     90          3            6            4  
64650     0       0       1   27     55          4            4            3  
64651     0       1       0   25     40          4            3            3

In [8]:
def transform_bmi(bmi):
    if bmi <= 18 :
        return 1
    elif bmi >= 19 and bmi <= 24:
        return 2
    elif bmi >= 25 and bmi <= 29:
        return 3
    elif bmi >= 30 and bmi <= 100:
        return 4
   

clean_df = clean_df.assign(final_bmi = clean_df['bmi'].apply(transform_bmi))
clean_df.tail()
    

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
64647   53       2     168      76    120     80            1     1      1   
64648   62       1     158     126    140     90            2     2      0   
64649   52       2     183     105    180     90            3     1      0   
64650   61       1     163      72    135     80            1     2      0   
64651   56       1     170      72    120     80            2     1      0   

       alco  active  cardio  bmi  pulse  final_age  final_ap_hi  final_ap_lo  \
64647     0       1       0   27     40          3            3            3   
64648     0       1       1   50     50          5            5            4   
64649     1       0       1   31     90          3            6            4   
64650     0       0       1   27     55          4            4            3   
64651     0       1       0   25     40          4            3            3   

       final_bmi  
64647          3  
64648          4  
64649          4  
64650          3  
64651          3

In [9]:
Y = clean_df.iloc[:,11].values
X = clean_df.drop(['cardio', 'height','smoke','active','alco','gender','pulse','age','weight','ap_hi','ap_lo','bmi'], axis =1)


In [10]:
X.head()

cholesterol  gluc  final_age  final_ap_hi  final_ap_lo  final_bmi
0            1     1          3            2            3          2
1            3     1          4            5            4          4
2            3     1          3            4            2          2
3            1     1          3            5            5          3
4            1     1          3            2            1          2

In [11]:
X.shape

(64652, 6)

In [81]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64652 entries, 0 to 64651
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          64652 non-null  int64
 1   weight       64652 non-null  int64
 2   ap_hi        64652 non-null  int64
 3   ap_lo        64652 non-null  int64
 4   cholesterol  64652 non-null  int64
 5   gluc         64652 non-null  int64
 6   bmi          64652 non-null  int64
dtypes: int64(7)
memory usage: 3.5 MB


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42, shuffle = True)

In [43]:
X_train

cholesterol  gluc  final_age  final_ap_hi  final_ap_lo  final_bmi
5389             1     1          4            2            3          3
48468            1     1          4            3            3          3
58708            2     1          4            2            1          3
48707            1     1          4            5            5          3
60032            1     1          3            3            3          3
...            ...   ...        ...          ...          ...        ...
62570            1     1          4            5            5          3
38158            3     1          4            4            3          3
860              1     1          3            3            3          2
15795            1     1          3            3            3          2
56422            1     1          3            3            3          2

[48489 rows x 6 columns]

In [83]:
y_test

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [40]:
# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)

In [13]:
#my_list=[40,65,120,80,1,1,21]
svmrbf=SVC(C=1, gamma='auto', kernel='rbf')
svmrbf.fit(X_train,y_train)
svm_pred=svmrbf.predict(X_test)
#svm_pred1=svmrbf.predict(my_list)
accuracy_score=(y_test,svm_pred)
#print(svm_pred1)
print(accuracy_score)



(array([0, 0, 1, ..., 0, 0, 0], dtype=int64), array([0, 0, 1, ..., 1, 1, 1], dtype=int64))


In [14]:
svmpoly=SVC(kernel='poly',degree=3)
svmpoly.fit(X_train,y_train)
svm_pred=svmpoly.predict(X_test)
#svm_pred1=svmpoly.predict(my_list)
accuracy_score=(y_test,svm_pred)
print(accuracy_score)

(array([0, 0, 1, ..., 0, 0, 0], dtype=int64), array([0, 0, 1, ..., 1, 0, 1], dtype=int64))


In [15]:
svmlinear=SVC(kernel='linear')
svmlinear.fit(X_train,y_train)
svm_pred=svmlinear.predict(X_test)
#svm_pred1=svmlinear.predict(my_list)
accuracy_score=(y_test,svm_pred)
print(accuracy_score)

(array([0, 0, 1, ..., 0, 0, 0], dtype=int64), array([0, 0, 1, ..., 0, 0, 1], dtype=int64))


In [16]:
dt=DecisionTreeClassifier(class_weight= None, criterion='entropy', max_depth=7, presort=True)
dt.fit(X_train,y_train)
dt_pred=dt.predict(X_test)
#dt_pred1=dt.predict(my_list)
accuracy_score=(y_test,svm_pred)
print(accuracy_score)

(array([0, 0, 1, ..., 0, 0, 0], dtype=int64), array([0, 0, 1, ..., 0, 0, 1], dtype=int64))


In [17]:
rf=RandomForestClassifier(bootstrap=True, criterion='gini', max_features='auto', min_samples_leaf=4, min_samples_split= 2, n_estimators=100, n_jobs= -1, oob_score=True, random_state=42, warm_start=True)
rf.fit(X_train,y_train)
rf_pred=rf.predict(X_test)
accuracy_score=(y_test,rf_pred)
print(accuracy_score)

(array([0, 0, 1, ..., 0, 0, 0], dtype=int64), array([0, 0, 1, ..., 1, 0, 1], dtype=int64))


In [88]:
# xgb=XGBClassifier(colsample_bytree= 0.6, gamma=2, max_depth=3, min_child_weight= 10, subsample= 1.0)
# xgb.fit(X_train,y_train)
# xgb_pred=xgb.predict(X_test)
# #xgb_pred1=xgb.predict(my_list)
# accuracy_score=(y_test,svm_pred)
# print(accuracy_score)

(array([0, 0, 1, ..., 0, 0, 0], dtype=int64), array([0, 0, 1, ..., 1, 0, 1], dtype=int64))


In [18]:
lr=LogisticRegression(C= 0.1,class_weight={1: 0.5, 0: 0.5}, penalty='l2',solver='liblinear')
lr.fit(X_train,y_train)
lr_pred=lr.predict(X_test)
#lr_pred1=lr.predict(my_list)
accuracy_score=(y_test,svm_pred)
print(accuracy_score)

(array([0, 0, 1, ..., 0, 0, 0], dtype=int64), array([0, 0, 1, ..., 0, 0, 1], dtype=int64))


In [62]:
# import pickle
# with open('svm_rbf.pkl','wb') as f:
#     pickle.dump(svmrbf,f)

In [56]:
import pickle
with open('svm_rbf.pkl','wb') as f:
     pickle.dump(svmrbf,f)
    
with open('svm_poly.pkl','wb') as f:
     pickle.dump(svmpoly,f)
    
with open('svm_linear.pkl','wb') as f:
     pickle.dump(svmlinear,f)
    
with open('lr.pkl','wb') as f:
     pickle.dump(lr,f)
    
# with open('knn.pkl','wb') as f:
#      pickle.dump(knn,f)
    
with open('dt.pkl','wb') as f:
     pickle.dump(dt,f)
    
with open('rf.pkl','wb') as f:
      pickle.dump(rf,f)

# with open('xgb.pkl','wb') as f:
#      pickle.dump(xgb,f)

In [57]:
with open('dt.pkl', 'rb') as f:
    dt_model = pickle.load(f)

with open('lr.pkl', 'rb') as f:
    logistic_model = pickle.load(f)

with open('svm_linear.pkl', 'rb') as f:
    svm_linear_model = pickle.load(f)

with open('svm_poly.pkl', 'rb') as f:
     svm_poly_model = pickle.load(f)
    
with open('svm_rbf.pkl', 'rb') as f:
    svm_rbf_model = pickle.load(f)

with open('rf.pkl', 'rb') as f:
     rf_model = pickle.load(f)

    

In [52]:
#req_model='SvmRbf'
def get_predictions(cholesterol, gluc,age,  ap_hi, ap_lo, bmi, req_model):
    mylist = [cholesterol, gluc, age, ap_hi, ap_lo, bmi]
    mylist = [float(i) for i in mylist]
    vals = [mylist]

    if req_model == 'Logistic':
        #print(req_model)
        return logistic_model.predict(vals)[0]

    elif req_model == 'DecisionTree':
         #print(req_model)
        return dt_model.predict(vals)[0]

    elif req_model == 'SvmLinear':
         #print(req_model)
        return svm_linear_model.predict(vals)[0]
    
    elif req_model == 'SvmPoly':
         #print(req_model)
        return svm_poly_model.predict(vals)[0]
    
    elif req_model == 'SvmRbf':
        #print(req_model)
        return svm_rbf_model.predict(vals)[0]    
    
    elif req_model == 'RandomForest':
          #print(req_model)
        return rf_model.predict(vals)[0]    
    else:
        return "Cannot Predict"

In [55]:
get_predictions(3,3,4,3,2,3,'SvmPoly')

1